// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.hualala.aleenjava.grpc.user;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 id = 2;</code>
   * @return The id.
   */
  long getId();
}
