// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.hualala.aleenjava.grpc.user;

public interface UserPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string nick = 2;</code>
   * @return The nick.
   */
  java.lang.String getNick();
  /**
   * <code>string nick = 2;</code>
   * @return The bytes for nick.
   */
  com.google.protobuf.ByteString
      getNickBytes();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string phone = 4;</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 4;</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>double balance = 5;</code>
   * @return The balance.
   */
  double getBalance();

  /**
   * <code>int64 bornAt = 6;</code>
   * @return The bornAt.
   */
  long getBornAt();

  /**
   * <code>int64 flag = 7;</code>
   * @return The flag.
   */
  long getFlag();

  /**
   * <code>int64 vip = 8;</code>
   * @return The vip.
   */
  long getVip();
}
