// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.hualala.aleenjava.grpc.user;

/**
 * Protobuf type {@code UserReply}
 */
public final class UserReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UserReply)
    UserReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserReply.newBuilder() to construct.
  private UserReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserReply() {
    msg_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            code_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            msg_ = s;
            break;
          }
          case 24: {

            success_ = input.readBool();
            break;
          }
          case 34: {
            com.hualala.aleenjava.grpc.user.UserReply.Data.Builder subBuilder = null;
            if (data_ != null) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(com.hualala.aleenjava.grpc.user.UserReply.Data.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hualala.aleenjava.grpc.user.User.internal_static_UserReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hualala.aleenjava.grpc.user.User.internal_static_UserReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hualala.aleenjava.grpc.user.UserReply.class, com.hualala.aleenjava.grpc.user.UserReply.Builder.class);
  }

  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserReply.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.UserPb userPb = 1;</code>
     * @return Whether the userPb field is set.
     */
    boolean hasUserPb();
    /**
     * <code>.UserPb userPb = 1;</code>
     * @return The userPb.
     */
    com.hualala.aleenjava.grpc.user.UserPb getUserPb();
    /**
     * <code>.UserPb userPb = 1;</code>
     */
    com.hualala.aleenjava.grpc.user.UserPbOrBuilder getUserPbOrBuilder();
  }
  /**
   * Protobuf type {@code UserReply.Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserReply.Data)
      DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Data();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.hualala.aleenjava.grpc.user.UserPb.Builder subBuilder = null;
              if (userPb_ != null) {
                subBuilder = userPb_.toBuilder();
              }
              userPb_ = input.readMessage(com.hualala.aleenjava.grpc.user.UserPb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userPb_);
                userPb_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hualala.aleenjava.grpc.user.User.internal_static_UserReply_Data_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hualala.aleenjava.grpc.user.User.internal_static_UserReply_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hualala.aleenjava.grpc.user.UserReply.Data.class, com.hualala.aleenjava.grpc.user.UserReply.Data.Builder.class);
    }

    public static final int USERPB_FIELD_NUMBER = 1;
    private com.hualala.aleenjava.grpc.user.UserPb userPb_;
    /**
     * <code>.UserPb userPb = 1;</code>
     * @return Whether the userPb field is set.
     */
    @java.lang.Override
    public boolean hasUserPb() {
      return userPb_ != null;
    }
    /**
     * <code>.UserPb userPb = 1;</code>
     * @return The userPb.
     */
    @java.lang.Override
    public com.hualala.aleenjava.grpc.user.UserPb getUserPb() {
      return userPb_ == null ? com.hualala.aleenjava.grpc.user.UserPb.getDefaultInstance() : userPb_;
    }
    /**
     * <code>.UserPb userPb = 1;</code>
     */
    @java.lang.Override
    public com.hualala.aleenjava.grpc.user.UserPbOrBuilder getUserPbOrBuilder() {
      return getUserPb();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userPb_ != null) {
        output.writeMessage(1, getUserPb());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userPb_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUserPb());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hualala.aleenjava.grpc.user.UserReply.Data)) {
        return super.equals(obj);
      }
      com.hualala.aleenjava.grpc.user.UserReply.Data other = (com.hualala.aleenjava.grpc.user.UserReply.Data) obj;

      if (hasUserPb() != other.hasUserPb()) return false;
      if (hasUserPb()) {
        if (!getUserPb()
            .equals(other.getUserPb())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserPb()) {
        hash = (37 * hash) + USERPB_FIELD_NUMBER;
        hash = (53 * hash) + getUserPb().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hualala.aleenjava.grpc.user.UserReply.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hualala.aleenjava.grpc.user.UserReply.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hualala.aleenjava.grpc.user.UserReply.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hualala.aleenjava.grpc.user.UserReply.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hualala.aleenjava.grpc.user.UserReply.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hualala.aleenjava.grpc.user.UserReply.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hualala.aleenjava.grpc.user.UserReply.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hualala.aleenjava.grpc.user.UserReply.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hualala.aleenjava.grpc.user.UserReply.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hualala.aleenjava.grpc.user.UserReply.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hualala.aleenjava.grpc.user.UserReply.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hualala.aleenjava.grpc.user.UserReply.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hualala.aleenjava.grpc.user.UserReply.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserReply.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserReply.Data)
        com.hualala.aleenjava.grpc.user.UserReply.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hualala.aleenjava.grpc.user.User.internal_static_UserReply_Data_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hualala.aleenjava.grpc.user.User.internal_static_UserReply_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hualala.aleenjava.grpc.user.UserReply.Data.class, com.hualala.aleenjava.grpc.user.UserReply.Data.Builder.class);
      }

      // Construct using com.hualala.aleenjava.grpc.user.UserReply.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (userPbBuilder_ == null) {
          userPb_ = null;
        } else {
          userPb_ = null;
          userPbBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hualala.aleenjava.grpc.user.User.internal_static_UserReply_Data_descriptor;
      }

      @java.lang.Override
      public com.hualala.aleenjava.grpc.user.UserReply.Data getDefaultInstanceForType() {
        return com.hualala.aleenjava.grpc.user.UserReply.Data.getDefaultInstance();
      }

      @java.lang.Override
      public com.hualala.aleenjava.grpc.user.UserReply.Data build() {
        com.hualala.aleenjava.grpc.user.UserReply.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hualala.aleenjava.grpc.user.UserReply.Data buildPartial() {
        com.hualala.aleenjava.grpc.user.UserReply.Data result = new com.hualala.aleenjava.grpc.user.UserReply.Data(this);
        if (userPbBuilder_ == null) {
          result.userPb_ = userPb_;
        } else {
          result.userPb_ = userPbBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hualala.aleenjava.grpc.user.UserReply.Data) {
          return mergeFrom((com.hualala.aleenjava.grpc.user.UserReply.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hualala.aleenjava.grpc.user.UserReply.Data other) {
        if (other == com.hualala.aleenjava.grpc.user.UserReply.Data.getDefaultInstance()) return this;
        if (other.hasUserPb()) {
          mergeUserPb(other.getUserPb());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hualala.aleenjava.grpc.user.UserReply.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hualala.aleenjava.grpc.user.UserReply.Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.hualala.aleenjava.grpc.user.UserPb userPb_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hualala.aleenjava.grpc.user.UserPb, com.hualala.aleenjava.grpc.user.UserPb.Builder, com.hualala.aleenjava.grpc.user.UserPbOrBuilder> userPbBuilder_;
      /**
       * <code>.UserPb userPb = 1;</code>
       * @return Whether the userPb field is set.
       */
      public boolean hasUserPb() {
        return userPbBuilder_ != null || userPb_ != null;
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       * @return The userPb.
       */
      public com.hualala.aleenjava.grpc.user.UserPb getUserPb() {
        if (userPbBuilder_ == null) {
          return userPb_ == null ? com.hualala.aleenjava.grpc.user.UserPb.getDefaultInstance() : userPb_;
        } else {
          return userPbBuilder_.getMessage();
        }
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       */
      public Builder setUserPb(com.hualala.aleenjava.grpc.user.UserPb value) {
        if (userPbBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userPb_ = value;
          onChanged();
        } else {
          userPbBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       */
      public Builder setUserPb(
          com.hualala.aleenjava.grpc.user.UserPb.Builder builderForValue) {
        if (userPbBuilder_ == null) {
          userPb_ = builderForValue.build();
          onChanged();
        } else {
          userPbBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       */
      public Builder mergeUserPb(com.hualala.aleenjava.grpc.user.UserPb value) {
        if (userPbBuilder_ == null) {
          if (userPb_ != null) {
            userPb_ =
              com.hualala.aleenjava.grpc.user.UserPb.newBuilder(userPb_).mergeFrom(value).buildPartial();
          } else {
            userPb_ = value;
          }
          onChanged();
        } else {
          userPbBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       */
      public Builder clearUserPb() {
        if (userPbBuilder_ == null) {
          userPb_ = null;
          onChanged();
        } else {
          userPb_ = null;
          userPbBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       */
      public com.hualala.aleenjava.grpc.user.UserPb.Builder getUserPbBuilder() {
        
        onChanged();
        return getUserPbFieldBuilder().getBuilder();
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       */
      public com.hualala.aleenjava.grpc.user.UserPbOrBuilder getUserPbOrBuilder() {
        if (userPbBuilder_ != null) {
          return userPbBuilder_.getMessageOrBuilder();
        } else {
          return userPb_ == null ?
              com.hualala.aleenjava.grpc.user.UserPb.getDefaultInstance() : userPb_;
        }
      }
      /**
       * <code>.UserPb userPb = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hualala.aleenjava.grpc.user.UserPb, com.hualala.aleenjava.grpc.user.UserPb.Builder, com.hualala.aleenjava.grpc.user.UserPbOrBuilder> 
          getUserPbFieldBuilder() {
        if (userPbBuilder_ == null) {
          userPbBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.hualala.aleenjava.grpc.user.UserPb, com.hualala.aleenjava.grpc.user.UserPb.Builder, com.hualala.aleenjava.grpc.user.UserPbOrBuilder>(
                  getUserPb(),
                  getParentForChildren(),
                  isClean());
          userPb_ = null;
        }
        return userPbBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserReply.Data)
    }

    // @@protoc_insertion_point(class_scope:UserReply.Data)
    private static final com.hualala.aleenjava.grpc.user.UserReply.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hualala.aleenjava.grpc.user.UserReply.Data();
    }

    public static com.hualala.aleenjava.grpc.user.UserReply.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      @java.lang.Override
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hualala.aleenjava.grpc.user.UserReply.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  @java.lang.Override
  public int getCode() {
    return code_;
  }

  public static final int MSG_FIELD_NUMBER = 2;
  private volatile java.lang.Object msg_;
  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  @java.lang.Override
  public java.lang.String getMsg() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgBytes() {
    java.lang.Object ref = msg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUCCESS_FIELD_NUMBER = 3;
  private boolean success_;
  /**
   * <code>bool success = 3;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int DATA_FIELD_NUMBER = 4;
  private com.hualala.aleenjava.grpc.user.UserReply.Data data_;
  /**
   * <code>.UserReply.Data data = 4;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <code>.UserReply.Data data = 4;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.hualala.aleenjava.grpc.user.UserReply.Data getData() {
    return data_ == null ? com.hualala.aleenjava.grpc.user.UserReply.Data.getDefaultInstance() : data_;
  }
  /**
   * <code>.UserReply.Data data = 4;</code>
   */
  @java.lang.Override
  public com.hualala.aleenjava.grpc.user.UserReply.DataOrBuilder getDataOrBuilder() {
    return getData();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (!getMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
    }
    if (success_ != false) {
      output.writeBool(3, success_);
    }
    if (data_ != null) {
      output.writeMessage(4, getData());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, code_);
    }
    if (!getMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
    }
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, success_);
    }
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hualala.aleenjava.grpc.user.UserReply)) {
      return super.equals(obj);
    }
    com.hualala.aleenjava.grpc.user.UserReply other = (com.hualala.aleenjava.grpc.user.UserReply) obj;

    if (getCode()
        != other.getCode()) return false;
    if (!getMsg()
        .equals(other.getMsg())) return false;
    if (getSuccess()
        != other.getSuccess()) return false;
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MSG_FIELD_NUMBER;
    hash = (53 * hash) + getMsg().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hualala.aleenjava.grpc.user.UserReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hualala.aleenjava.grpc.user.UserReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hualala.aleenjava.grpc.user.UserReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hualala.aleenjava.grpc.user.UserReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hualala.aleenjava.grpc.user.UserReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hualala.aleenjava.grpc.user.UserReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hualala.aleenjava.grpc.user.UserReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hualala.aleenjava.grpc.user.UserReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hualala.aleenjava.grpc.user.UserReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hualala.aleenjava.grpc.user.UserReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hualala.aleenjava.grpc.user.UserReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hualala.aleenjava.grpc.user.UserReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hualala.aleenjava.grpc.user.UserReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UserReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UserReply)
      com.hualala.aleenjava.grpc.user.UserReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hualala.aleenjava.grpc.user.User.internal_static_UserReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hualala.aleenjava.grpc.user.User.internal_static_UserReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hualala.aleenjava.grpc.user.UserReply.class, com.hualala.aleenjava.grpc.user.UserReply.Builder.class);
    }

    // Construct using com.hualala.aleenjava.grpc.user.UserReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      code_ = 0;

      msg_ = "";

      success_ = false;

      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        data_ = null;
        dataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hualala.aleenjava.grpc.user.User.internal_static_UserReply_descriptor;
    }

    @java.lang.Override
    public com.hualala.aleenjava.grpc.user.UserReply getDefaultInstanceForType() {
      return com.hualala.aleenjava.grpc.user.UserReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.hualala.aleenjava.grpc.user.UserReply build() {
      com.hualala.aleenjava.grpc.user.UserReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hualala.aleenjava.grpc.user.UserReply buildPartial() {
      com.hualala.aleenjava.grpc.user.UserReply result = new com.hualala.aleenjava.grpc.user.UserReply(this);
      result.code_ = code_;
      result.msg_ = msg_;
      result.success_ = success_;
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hualala.aleenjava.grpc.user.UserReply) {
        return mergeFrom((com.hualala.aleenjava.grpc.user.UserReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hualala.aleenjava.grpc.user.UserReply other) {
      if (other == com.hualala.aleenjava.grpc.user.UserReply.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMsg().isEmpty()) {
        msg_ = other.msg_;
        onChanged();
      }
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hualala.aleenjava.grpc.user.UserReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hualala.aleenjava.grpc.user.UserReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int code_ ;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object msg_ = "";
    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @param value The msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsg() {
      
      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 2;</code>
     * @param value The bytes for msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msg_ = value;
      onChanged();
      return this;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 3;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 3;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private com.hualala.aleenjava.grpc.user.UserReply.Data data_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hualala.aleenjava.grpc.user.UserReply.Data, com.hualala.aleenjava.grpc.user.UserReply.Data.Builder, com.hualala.aleenjava.grpc.user.UserReply.DataOrBuilder> dataBuilder_;
    /**
     * <code>.UserReply.Data data = 4;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return dataBuilder_ != null || data_ != null;
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     * @return The data.
     */
    public com.hualala.aleenjava.grpc.user.UserReply.Data getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.hualala.aleenjava.grpc.user.UserReply.Data.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     */
    public Builder setData(com.hualala.aleenjava.grpc.user.UserReply.Data value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     */
    public Builder setData(
        com.hualala.aleenjava.grpc.user.UserReply.Data.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     */
    public Builder mergeData(com.hualala.aleenjava.grpc.user.UserReply.Data value) {
      if (dataBuilder_ == null) {
        if (data_ != null) {
          data_ =
            com.hualala.aleenjava.grpc.user.UserReply.Data.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        data_ = null;
        dataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     */
    public com.hualala.aleenjava.grpc.user.UserReply.Data.Builder getDataBuilder() {
      
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     */
    public com.hualala.aleenjava.grpc.user.UserReply.DataOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.hualala.aleenjava.grpc.user.UserReply.Data.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.UserReply.Data data = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hualala.aleenjava.grpc.user.UserReply.Data, com.hualala.aleenjava.grpc.user.UserReply.Data.Builder, com.hualala.aleenjava.grpc.user.UserReply.DataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.hualala.aleenjava.grpc.user.UserReply.Data, com.hualala.aleenjava.grpc.user.UserReply.Data.Builder, com.hualala.aleenjava.grpc.user.UserReply.DataOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UserReply)
  }

  // @@protoc_insertion_point(class_scope:UserReply)
  private static final com.hualala.aleenjava.grpc.user.UserReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hualala.aleenjava.grpc.user.UserReply();
  }

  public static com.hualala.aleenjava.grpc.user.UserReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserReply>
      PARSER = new com.google.protobuf.AbstractParser<UserReply>() {
    @java.lang.Override
    public UserReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hualala.aleenjava.grpc.user.UserReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

